#!/usr/bin/env bash
# Change DNS resolutions

# Backup original hosts file
cp /etc/hosts /etc/hosts.backup

# Update localhost to 127.0.0.2 and facebook.com to 8.8.8.8
sed -i 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/g' /etc/hosts
echo "8.8.8.8    facebook.com" >> /etc/hosts
